name: Run script.sh

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run script.sh
        run: |
          cd remix-cf-pages
          npm uninstall -g @cloudflare/wrangler && npm install -g wrangler
          npm run deploy
